MvcProjeKampim/Controllers/HeadingController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampim.Controllers
{
    public class HeadingController : Controller
    {
        // GET: Heading
        HeadingManager hm = new HeadingManager(new EfHeadingDal());
        CategoryManager cm = new CategoryManager(new EfCategoryDal());
        WriterManager wm = new WriterManager(new EfWriterDal());
        Context c = new Context();
        public ActionResult Index()
        {
            var headingvalues = hm.GetList();
            return View(headingvalues.ToList());
        }
        public ActionResult GetAllHeading(string p)
        {
            var values = hm.GetHeadingList(p);
            return View(values.ToList());
        }
        public ActionResult HeadingReport()
        {
            var headingvalues = hm.GetList();
            return View(headingvalues.ToList());
        }

        [HttpGet]
        public ActionResult AddHeading()
        {
            List<SelectListItem> valuecategory = (from x in cm.GetCategoryList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.CategoryName,
                                                      Value = x.CategoryID.ToString()

                                                  }).ToList();
            ViewBag.vlc = valuecategory;

            List<SelectListItem> valuewriter = (from x in wm.GetList()
                                                select new SelectListItem
                                                {
                                                    Text = x.WriterName + " " + x.WriterSurname,
                                                    Value = x.WriterID.ToString()
                                                }
                                                ).ToList();

            ViewBag.vlw = valuewriter;
            return View();
        }

        [HttpPost]
        public ActionResult AddHeading(Heading p)
        {
            p.HeadingDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            hm.HeadingAdd(p);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult EditHeading(int id)
        {
            List<SelectListItem> valuecategory = (from x in cm.GetCategoryList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.CategoryName,
                                                      Value = x.CategoryID.ToString()

                                                  }).ToList();
            ViewBag.vlc = valuecategory;

            List<SelectListItem> valuewriter = (from x in wm.GetList()
                                                select new SelectListItem
                                                {
                                                    Text = x.WriterName + " " + x.WriterSurname,
                                                    Value = x.WriterID.ToString()
                                                }
                                           ).ToList();

            ViewBag.vlw = valuewriter;

            var HeadingValue = hm.GetByID(id);
            return View(HeadingValue);
        }
        [HttpPost]
        public ActionResult EditHeading(Heading p)
        {
            hm.HeadingUpdate(p);
            return RedirectToAction("Index");
        }
        public ActionResult DeleteHeading(int id)
        {
            var headingvalue = hm.GetByID(id);
            headingvalue.HeadingStatus = headingvalue.HeadingStatus == true ? false : true;
            hm.HeadingDelete(headingvalue);

            return RedirectToAction("Index");
        }
    }
}

MvcProjeKampim/Views/Heading/AddHeading.cshtml
@model EntityLayer.Concrete.Heading
@{
    ViewBag.Title = "AddHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h1>Yeni Başlık Ekleme Sayfası</h1>
<br />
@using (Html.BeginForm("AddHeading", "Heading", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Başlık Adı")
        @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.HeadingName)
        <br />
        @Html.Label("Kategori")
        @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
        <br />
        @Html.Label("Yazar")
        @Html.DropDownListFor(x => x.WriterID, (List<SelectListItem>)ViewBag.vlw, new { @class = "form-control" })
        <br />
        <button class="btn btn-outline-primary">Başlığı Oluştur</button>
    </div>
}

MvcProjeKampim/Views/Heading/EditHeading.cshtml
@model EntityLayer.Concrete.Heading
@{
    ViewBag.Title = "EditHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Başlık Güncelleme Sayfası</h1>
<br />
@using (Html.BeginForm("EditHeading", "Heading", FormMethod.Post))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.HeadingID, new { @class = "form-control" })
        @Html.HiddenFor(x => x.HeadingDate, new { @class = "form-control" })
        @Html.HiddenFor(x => x.WriterID, new { @class = "form-control" })
        <br />
        @Html.Label("Başlık İsmi")
        @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
        <br />
        @Html.Label("Kategori")
        @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.vlc,"Kategori Seçiniz...", new { @class = "form-control" })
        <br />
        <button class="btn btn-outline-success">Güncelle</button>
    </div>
}

MvcProjeKampim/Views/Heading/HeadingReport.cshtml
@using EntityLayer.Concrete
@model List<Heading>
@{
    ViewBag.Title = "HeadingReport";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Mvc Pro Kampı Raporlama Sayfası</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap4.min.css">
</head>
<body>
    <table id="example" class="table table-striped table-bordered dt-responsive nowrap" style="width:100%">
        <thead>
            <tr>
                <th>Başlık ID</th>
                <th>Başlık Adı</th>
                <th>Tarih</th>
                <th>Yazar</th>
                <th>Kategori</th>
                <th>Durum</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var x in Model)
            {
                <tr>
                    <td>@x.HeadingID</td>
                    <td>@x.HeadingName</td>
                    <td>@(((DateTime)x.HeadingDate).ToShortDateString())</td>
                    <td>@x.Writer.WriterName @x.Writer.WriterSurname</td>
                    <td>@x.Category.CategoryName</td>
                    <td>@x.HeadingStatus</td>
                </tr>
            }

        </tbody>
    </table>
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.bootstrap4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.colVis.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function () {
            var table = $('#example').DataTable({

                dom: 'Bfrtip',
                buttons: [
                    'copy', 'excel', 'pdf', 'print'
                ],
                responsive: true,
                language: { url: '//cdn.datatables.net/plug-ins/2.0.3/i18n/tr.json' },

            });
        });</script>
</body>
</html>

MvcProjeKampim/Views/Heading/Index.cshtml
@using EntityLayer.Concrete
@model List<Heading>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@{ string color = ""; string durum = ""; string name = ""; string color2 = "";}

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Başlıklar Sayfası</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Başlık İşlemleri</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 20%">
                                Başlık Adı
                            </th>
                            <th style="width: 15%">
                                Oluşturan Yazar
                            </th>
                            <th style="width: 15%">
                                Durum
                            </th>
                            <th style="width: 8%" class="text-center">
                                Kategori
                            </th>
                            <th style="width: 20%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            if (item.HeadingStatus == true)
                            {
                                color = "badge badge-success";
                                color2 = "badge badge-danger";
                                name = "Pasif Yap";

                            }
                            if (item.HeadingStatus == false)
                            {
                                color = "badge badge-danger";
                                color2 = "badge badge-success";
                                name = "Aktif Yap";
                            }

                            switch (item.HeadingStatus)
                            {
                                case true:
                                    durum = "Aktif";
                                    break;
                                case false:
                                    durum = "Pasif";
                                    break;
                                default:
                                    break;
                            }
                            <tr>
                                <td>
                                    @item.HeadingID
                                </td>
                                <td>
                                    <a>
                                        @item.HeadingName
                                    </a>
                                    <br />
                                    <small>
                                        @(((DateTime)item.HeadingDate).ToString("dd-MMM-yyyy"))
                                        @*@item.HeadingDate.ToShortDateString()*@
                                    </small>
                                </td>
                                <td>
                                    <ul class="list-inline">
                                        <li class="list-inline-item">
                                            <img alt="Avatar" class="table-avatar" src="@item.Writer.WriterImage">
                                        </li>
                                    </ul>
                                </td>
                                <td>
                                    <span class="@color">@durum</span>
                                </td>
                                <td class="project-state">
                                    <span class="badge badge-success">@item.Category.CategoryName</span>
                                </td>
                                <td class="project-actions text-right">
                                    <a class="btn btn-primary btn-sm" href="/Content/ContentByHeading/@item.HeadingID">
                                        <i class="fas fa-folder">
                                        </i>
                                        Yazılar
                                    </a>
                                    <a class="btn btn-info btn-sm" href="/Heading/EditHeading/@item.HeadingID">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Düzenle
                                    </a>
                                    <a class="@color2" href="/Heading/DeleteHeading/@item.HeadingID">
                                        <i class="fas fa-trash">
                                        </i>
                                        @name
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </section>
</body>
</html>
<a href="/Heading/AddHeading" class="btn btn-outline-primary">Yeni Başlık Ekle</a>


@*<h2>Index</h2>
    <br />
    <table class="table table-bordered">
        <tr>
            <th>ID</th>
            <th>Başlık</th>
            <th>Kategori</th>
        </tr>
        @foreach(var item in Model)
        {
            <tr>
                <td>@item.HeadingID</td>
                <td>@item.HeadingName</td>
                <td>@item.Category.CategoryName</td>
            </tr>
        }
    </table>
    <br />
    <a href="/Heading/AddHeading" class="btn btn-info">Yeni başlık Girişi</a>*@
<script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.js"></script>